Jz/buzz on ready
StuyPulse/Jim pull request #169
Opened 2023-04-01 20:31 UTC by vincentw921

plz accept

2023-04-02 17:21 UTC, selym3 requested changes

2023-04-02 17:21 UTC, selym3 commented on src/main/java/com/stuypulse/robot/RobotContainer.java
> +                    .alongWith(new IntakeAcquire()).withTimeout(0.2)
it looks like this timeout went onto the whole commanf group, when it should just be only on the intake acquire, ALSO you need to stop the intake after this wait command.

so maybe it should be a group of 
intake acquire, wait 0.2 seconds, intake stop

2023-04-02 17:22 UTC, selym3 commented
Also I wonder if you can cancel the whole operation if it stalls, but with such a low time it takes in it's probably fine

2023-04-02 18:58 UTC, anivanchen requested changes

2023-04-02 18:58 UTC, anivanchen commented on src/main/java/com/stuypulse/robot/RobotContainer.java
> +            .onTrue(new IntakeAcquire().withTimeout(0.2))
The intake never stops. You need an IntakeStop after IntakeAcquire ends.

2023-04-02 21:14 UTC, selym3 requested changes

2023-04-02 21:14 UTC, selym3 commented on src/main/java/com/stuypulse/robot/RobotContainer.java
> +            .onTrue(new IntakeAcquire()
whileTrue so it ends when the button is let go of

2023-04-05 19:53 UTC, BenG49 approved these changes

2023-04-05 19:58 UTC, merged